### PR TITLE
Add some hyper links & section for historic libraries. 

### PR DESCRIPTION
**Pull request by bibliotechy**
You cn see these changes here http://c4l-phl.github.io/

### CODE REVIEW

**Comment by hackartisan** [comment]
Great. I think the rest of us have just been pushing straight to master; we didn't really discuss workflow here...

**Comment by bibliotechy** [comment]
@hackmastera Well, I made the changes in my forked repo, so it was pretty easy to just PR. And now I've merged my own PR, which I think means God just murdered an octocat

**Comment by hackartisan** [comment]
Man I would have done it for you! Now you go apologize to that octocat's mother!

**Comment by bibliotechy** [comment]
:joy_cat:

**Pull request merged**
